// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mveqkcrmdwwnmvepihtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12ZXFrY3JtZHd3bm12ZXBpaHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NjM2ODksImV4cCI6MjA2MzEzOTY4OX0.WbF4cQ0apOGPFwz35xwDOjLvS714ixO7c7K1UYBkF84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);